### ISSUE TITLE
CONTRIBUTING.md lacks links

### ISSUE THREAD

**Issue by filmaj** [adobe/stock-api-sdk#1]
- missing link/email where code of conduct violations can be reported
- missing link on where to sign / submit the CLA

**Comment by chfabbro** [comment]
Hi. The CLA is still being prepared by our legal team, but I did add a link for reporting violations.

Thanks for the report! I'll leave it open until the CLA is available.

**Comment by filmaj** [comment]
This is fixed! Closing.
